version: "3.3"
services:
  postgres:
    image: postgres:${CONTAINER_PG_VERSION:-10}
    environment:
      - POSTGRES_PASSWORD=postgres
  code:
    build:
      context: .
      args:
        - CONTAINER_PG_VERSION=${CONTAINER_PG_VERSION:-10}
        - CONTAINER_RUBY_VERSION=${CONTAINER_RUBY_VERSION:-2}
    image: pg_party
    environment:
      - CC_TEST_REPORTER_ID
    links:
      - postgres
    volumes:
      - .:/code
